FROM openjdk:8-jdk

COPY target/demo-microservice-webelement-0.0.1-SNAPSHOT.jar /opt/demo-microservice-webelement-0.0.1-SNAPSHOT.jar

CMD java -jar /opt/demo-microservice-webelement-0.0.1-SNAPSHOT.jar
